dist: xenial
addons:
  chrome: stable
language: node_js
install:
- npm ci
- npm run webdriver:update
cache:
  directories:
  - node_modules
env:
  global:
  - secure: imQwWv5jcJlGEPOSQPorAPSyWGMWz6EFIIlnQr/d3VYEM7SOMPY5PBD3SIbF2NAM9zNuuu/Pr80m11WQnwkK1zTevMEQTW2UGN2bAa01eXEGT2eThng9xSzOBK9FlZyFAAh9kkfkivhDUWsXueCicrlRDTAABLuWPHxPfv0c2yXLFVfcjN5YkeyK2coHEYUJeQ5gXfXxBhw4ALSgHXt7fC/F1pXjqFlY/BVAOz0qcU1P3x/5BdMFRwtntAe+XhYz5O8mkyurEVmOlMP+dbrg1lbiu4DJBISJwvykQWpT7TYwssBR6htZGbGlK0rPve9moKWICHmgMospP2smORqazegDTqOgo1D8Swx1SRld5bBytQAsw5+mOxVGDppmPPiO/zySXdLbCjAngC+w6h6qgv6HNbJyVzk3a/9NCXCcvpgq00tdON2Y+5L2qz158yft2IkhlzIFr6EfB/42WJZ2vC5kkjPz35mbUyWEO+ooTFJqoFWCs+gpumNJI5JJzDneqSoKRNhsGkFyC799Xp5oF6RFHlhLkoiRx/EnmVhO6mN8h6cj6mOJsZPglAP/H9KBm9XsKJH2jm2/cAtolsLEWTrpiXcIC2XCPGdPXu2Vy8WWI97vL8T3jrgzNUiHU0OdwblXNAzTgjg/3aFGYxi5s+ogcpmMvKPhMZq36M7G3Ek=
  - secure: n/IEzwhUW6zIA4ZryDriXirhfb9sdBpEVoA5d1aZcLgQrHfeSL8n263K6F+goF4VJcdA5/iKOgjLUBzqZpdWVb9BK42n0FJ+2bbQG4vbtXrl1w6vZRSSLsaqNrNQQaGYx201JEtqKwOTbSG/MnLY8pMuH6z0OLGpTjyubHy6VeRnRzPIJD3I6kWxJjNhO3PPKToqR36K/5M8tMYvdEBPeDkdRo5UzLcYEdAjnP5Y0QawwSK6ii19+432w8CpTON8KWa5Qq86YUHTfq1jn4ZkaUNYY7eobY2yFHb6UtT2P6mDGEQlZfVkC2zgEV4sLQlNv1r/KXCBR5LeAE+8MKlYwHPmPdwWWudSNk4sNCZTI9yuJCdvgNLLXl8BUF7fVpONg8fJQTkXzoQ0sfjfwKJD1eRTWsilCXd1jqKubb3HJMoLJb5laRS/NIEAGAA3aFbT29cPJ2pIhCSRhL9WvyI0EsvRpBYZUXzreCfo1ukdKZG84PyU8l4eaPe4ubi1aF2eappxv1PQ60BS5JiNvXpHlTP77Zb/dQSkh4qPCQKqUMJsgeMXSmT6tJuNgBKgL0hz3BEFiKbvqdVL6M9wJMeUYiX8Ow+KrrhYrikvDSL2SSw7DBHjIYGtlcL5dH4ZzJ74rxSE/wQRi6pJ/iyg5xs18JbqzSb2p8Fbwl7BuV6Piqw=
